services:
  mysql-source:
    image: mysql:8-oracle
    container_name: mysql-source
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=111
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL
    volumes:
      - ./mysql/source-init:/docker-entrypoint-initdb.d
    networks:
      - cdc-net

  mysql-sink:
    image: mysql:8-oracle
    container_name: mysql-sink
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --server-id=112
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL      
    volumes:
      - ./mysql/sink-init:/docker-entrypoint-initdb.d
    networks:
      - cdc-net

  kafka:
    image: 'apache/kafka:4.1.0'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 60s
      retries: 20
    networks:
      - cdc-net

  redis-standalone:
    image: redis:7.2.2
    ports:
      - '6379:6379'
    networks:
      - cdc-net

networks:
  cdc-net:
