[workspace]
packages = [
    "analytics_api", 
    "analyticsdb", 
    "cache_enricher", 
    "commons", 
    "data_ingestion", 
    "data_ingestion_svc",
    "kafka_consumer_svc",
    "stream_processor"
]
